kind: Deployment
apiVersion: apps/v1
metadata:
  name: trv-schedule
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trv-schedule
  template:
    metadata:
      labels:
        app: trv-schedule
    spec:
      containers:
      - image: nginx
        name: trv-schedule
        ports:
        - containerPort: 80
        volumeMounts:
        - name: web-data
          mountPath: /usr/share/nginx/html
      initContainers:
      - image: alpine/git
        name: git
        command:
        - sh
        - -c
        - >
          git clone --recurse-submodules -j8 https://github.com/kennedn/trv-schedule-app /html ||
          {
            cd /html;
            git reset --hard HEAD;
            git submodule foreach --recursive git reset --hard HEAD;
            git pull --recurse-submodules -j8;
          }
        volumeMounts:
        - name: web-data
          mountPath: /html
      volumes:
      - name: web-data
        emptyDir: {}
        
